### ISSUE TITLE
Got a weird 'Request url mismatch.'

### ISSUE THREAD

**Issue by xlozinguez** [blacksonic/ngx-http-test#3]
I get the following results:

```sh
Expected 'http://localhost:3001/accounts?slug=foo' to match 'http://localhost:3001/accounts?slug=foo', 'Request url mismatch.'.
          at BackendExpectation._verifyConnection (webpack:///~/ngx-http-test/src/backend-expectation.ts:30:0 <- config/spec-bundle.js:64473:40)
          at BackendExpectation.verify (webpack:///~/ngx-http-test/src/backend-expectation.ts:25:0 <- config/spec-bundle.js:64468:14)
          at FakeBackend._verifyExpectation (webpack:///~/ngx-http-test/src/fake-backend.ts:137:0 <- config/spec-bundle.js:64638:35)
          at SafeSubscriber._next (webpack:///~/ngx-http-test/src/fake-backend.ts:19:0 <- config/spec-bundle.js:64520:23)
          at SafeSubscriber.__tryOrUnsub (webpack:///~/rxjs/Subscriber.js:223:0 <- config/spec-bundle.js:640:16)
          at SafeSubscriber.next (webpack:///~/rxjs/Subscriber.js:172:0 <- config/spec-bundle.js:589:22)
          at Subscriber._next (webpack:///~/rxjs/Subscriber.js:125:0 <- config/spec-bundle.js:542:26)
          at Subscriber.next (webpack:///~/rxjs/Subscriber.js:89:0 <- config/spec-bundle.js:506:18)
          at Subject.next (webpack:///~/rxjs/Subject.js:55:0 <- config/spec-bundle.js:2218:25)
          at FakeBackend.MockBackend.createConnection (webpack:///~/@angular/http/bundles/http-testing.umd.js:153:0 <- config/spec-bundle.js:62620:30)
          at httpRequest (webpack:///~/@angular/http/src/http.js:19:0 <- config/spec-bundle.js:42142:20)
          at Http.request (webpack:///~/@angular/http/src/http.js:114:0 <- config/spec-bundle.js:42237:34)
          at Http.get (webpack:///~/@angular/http/src/http.js:125:0 <- config/spec-bundle.js:42248:21)
          at CompanyApiService.fetchCompanyDetails (webpack:///src/common/services/company.api.service.ts:9:643 <- config/spec-bundle.js:30069:662)
          at Object.<anonymous> (webpack:///src/common/services/company.api.service.spec.ts:30:0 <- config/spec-bundle.js:65392:21)
          at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:232:0 <- config/spec-bundle.js:51055:26)
          at ProxyZoneSpec.onInvoke (webpack:///~/zone.js/dist/proxy.js:79:0 <- config/spec-bundle.js:50719:39)
          at ZoneDelegate.invoke (webpack:///~/zone.js/dist/zone.js:231:0 <- config/spec-bundle.js:51054:32)
          at Zone.run (webpack:///~/zone.js/dist/zone.js:114:0 <- config/spec-bundle.js:50937:43)
          at Object.<anonymous> (webpack:///~/zone.js/dist/jasmine-patch.js:104:0 <- config/spec-bundle.js:50436:34)
          at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- config/spec-bundle.js:50464:42)
          at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- config/spec-bundle.js:50464:42)
          at ZoneQueueRunner.jasmine.QueueRunner.ZoneQueueRunner.execute (webpack:///~/zone.js/dist/jasmine-patch.js:132:0 <- config/spec-bundle.js:50464:42)
          at ZoneDelegate.invokeTask (webpack:///~/zone.js/dist/zone.js:265:0 <- config/spec-bundle.js:51088:35)
          at Zone.runTask (webpack:///~/zone.js/dist/zone.js:154:0 <- config/spec-bundle.js:50977:47)
          at drainMicroTaskQueue (webpack:///~/zone.js/dist/zone.js:401:0 <- config/spec-bundle.js:51224:35)
```

Here's my test:

```ts
    describe('#fetchCompanyDetails: ', () => {
        it('should call endpoint and return a company when succesful', (done) => {
            backend
                .expectGet(`${process.env.API_URL}/accounts?slug=foo`)
                .respond(company_mock);

            subject.fetchCompanyDetails('foo').subscribe((response) => {
                expect(response).toEqual(company_mock);
                done();
            });
        });
    });
```

and here is my code:

```ts
fetchCompanyDetails(slug: string): Observable<Company> {
        return this.http.get(`${this.API_PATH}?slug=${slug}`)
            .map(res => res.json()[0]);
    }
```

**Comment by xlozinguez** [comment]
It turns out the issue has to be with the fact that `expectGet` is performing a `.toMatch` which expects a regex. So escaping the url beforehand solves the issue. I'm creating a PR to highlight this. I will post it shortly.

**Comment by blacksonic** [comment]
String needs to be treated differently then regex. Wanted a toEqual for strings and toMatch for regexes. I speared the extra if case, this is the result.

**Comment by xlozinguez** [comment]
@blacksonic yes indeed, maybe my PR makes that clearer? I added a test in the spec to highlight the difference

**Comment by blacksonic** [comment]
I wanted regular expression matching AND string matching, now both work
